version: "2"

services:
  app:
    build: .
    environment:
      GET_CONSUL_HOST: "http://requestb.in/zn6p5gzn"
    command:
      - -resync
      - "5"
      - -internal
      # - consul://consul:8500
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock
      - ./entry.sh:/tmp/entry.sh

  consul:
    image: gliderlabs/consul-server:0.6
    command:
      - -dev
      - -ui
    ports:
      - 8500:8500 # API

  sample_a:
    image: renegare/ecsproxy:4af3de9
    environment:
      SERVICE_NAME: api
      SERVICE_TAGS: web,prod
    restart: always
    ports:
      - 3000:3000
