version: "2"

services:
  app:
    image: renegare/devops-registrator:latest
    command:
      - -resync
      - "5"
      - -retry-attempts
      - "-1"
      - -internal
      - consul://consul:8500
    # environment:
    #   GET_CONSUL_HOST: "http://10.0.2.2:3000/latest/meta-data/local-ipv4"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock
      - ./entry.sh:/tmp/entry.sh

  consul:
    image: gliderlabs/consul-server:0.6
    command:
      - -dev
      - -ui
    ports:
      - 8500:8500 # API

  sample_a:
    image: renegare/ecsproxy:4af3de9
    environment:
      SERVICE_NAME: sample_a
    restart: always
    ports:
      - 3000
